project_id = "lnoeofoucvyopmhcfwes"

[functions.chat-with-chapter]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.submit-quiz]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.generate-mindmap]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
